# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/customization/

# Appearance
appearance:
  theme_day: minimal
  theme_night: minimal
  font: minimal
  font_size: L

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Personal website for Garrett Hyde.'
    twitter: 'GarrettHyde'

# Site header
header:
  navbar:
    # Display the navigation bar?
    enable: true
    # Align menu links: left (l), center (c), or right (r)
    align: l
    # Display your site title or `assets/media/logo*` image in the nav bar?
    show_logo: true
    # Show a language chooser (if you have translated your site content)?
    show_translations: false
    # If `show_translations` is enabled, do you wish to display the current language name?
    show_language: false
    # Let the user override the default light/dark mode of your theme?
    show_day_night: true
    # Let the user search from the nav bar?
    show_search: false
    # Attempt to automatically highlight the active menu link? Can be disabled for complex sites.
    highlight_active_link: true

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features
features:
  syntax_highlighter:
    theme_light: github-light
    theme_dark: github-dark

# Site footer
footer:
  copyright:
    notice: '© 2009–{year} Garrett Hyde. All rights reserved.'
    license:
      enable: false
      allow_derivatives: false
      share_alike: false
      allow_commercial: false
  show_translations: false
