---
dist: xenial
language: minimal

# Install packages
addons:
  apt:
    packages:
    - wget

env:
  HUGO_PACKAGE: https://github.com/gohugoio/hugo/releases/download/v0.86.0/hugo_extended_0.86.0_Linux-64bit.deb

install:
  # Install Hugo
  - |
    wget -q -O /tmp/hugo.deb "$HUGO_PACKAGE"
    sudo apt install /tmp/hugo.deb
    rm /tmp/hugo.deb

  # Check Hugo version
  - hugo version

script:
  - hugo

# Docs: https://docs.travis-ci.com/user/deployment/pages/
deploy:
  provider: pages
  fqdn: www.garretthyde.com
  local_dir: public
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    branch: master
